/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'GetInterviewDetails': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetCandidateDetails': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserSignup': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserLogin': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'SendScheduledInterviewMail': EventHandler<never, never>
    'SendRescheduledInterviewMail': EventHandler<never, never>
    'ScheduleInterview': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'schedule.interview.mail'; data: never }>
    'RescheduleInterview': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'reschedule.interview.mail'; data: never }>
    'GetAllInterviews': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CancelInterview': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetCandidateResumeProfile': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ViewResume': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetCandidateInterviews': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetAllCandidates': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GenerateResumeProfile': EventHandler<never, never>
    'DeleteCandidate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateCandidate': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'generate.resume.profile'; data: never }>
    'GetAnalytics': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}