/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GetTTSAudio': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ProcessFailedInterviews': CronHandler<never>
    'CancelPendingRescheduledInterviews': CronHandler<never>
    'StartCandidateInterviewStream': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'StartCandidateInterviewSession': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetInterviewDetails': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetInterviewAnalytics': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetCandidateInterviewsDetails': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GenerateCandidateInterviewProfile': EventHandler<never, never>
    'EndCandidateInterviewSession': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'generate-candidate-interview-profile'; data: never }>
    'StartInterviewSession': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GenerateResponse': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GenerateInterviewQuestion': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GenerateInterviewProfile': EventHandler<never, never>
    'GenerateFeedback': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'EndInterviewSession': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'generate-interview-profile'; data: never }>
    'GetCandidateDetails': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserSignup': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'UserLogin': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetAssemblyAIToken': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'StartAdminInterviewStream': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'SendScheduledInterviewMail': EventHandler<never, never>
    'SendRescheduledInterviewMail': EventHandler<never, never>
    'ScheduleInterview': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'schedule-interview-mail'; data: never }>
    'RescheduleInterview': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'reschedule-interview-mail'; data: never }>
    'GetInterviewDetailsByAdmin': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetAllInterviews': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CancelInterview': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetCandidateResumeProfile': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ViewResume': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetCandidateInterviews': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetAllCandidates': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GenerateResumeProfile': EventHandler<never, never>
    'DeleteCandidate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateCandidate': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'generate-resume-profile'; data: never }>
    'GetAnalytics': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}